---
spring:
  application.name: sample-boot-hibernate
  messages.basename: messages-validation, messages
  banner.location: banner.txt
  cache.jcache.config: classpath:ehcache.xml
  jackson.serialization:
    indent-output: true
  servlet.multipart:
    max-file-size: 20MB
    max-request-size: 20MB
  jpa.open-in-view: false

logging.config: classpath:logback-spring.xml

server:
  port: 8080

management:
  endpoints.web:
    base-path: /management
    exposure.include: "*"

extension:
  security:
    cors.enabled: true
    auth:
      enabled: false
      admin: false
  datasource:
    default:
      url: ${DB_DEFAULT_JDBC_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
      username: ${DB_DEFAULT_JDBC_USERNAME:}
      password: ${DB_DEFAULT_JDBC_PASSWORD:}
      jpa:
        package-to-scan: sample.model
        hibernate.ddl-auto: create-drop
    system:
      url: ${DB_SYSTEM_JDBC_URL:jdbc:h2:mem:system;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
      username: ${DB_SYSTEM_JDBC_USERNAME:}
      password: ${DB_SYSTEM_JDBC_PASSWORD:}
      jpa:
        package-to-scan: sample.context
        hibernate.ddl-auto: create-drop
  mail.enabled: false
  datafixture.enabled: true

---
spring.config.activate.on-profile: production

extension:
  datasource:
    default:
      jpa:
        hibernate.ddl-auto: none
    system:
      jpa:
        hibernate.ddl-auto: none
  security:
    auth.enabled: true
    cors.enabled: false
  datafixture.enabled: false

---
spring.config.activate.on-profile: admin

server.port: 8081

extension: 
  security.auth.admin: true
